### PR TITLE
[16.0][ADD] product_cost_extra: New module

### PR DESCRIPTION
**Pull request by pilarvargas-tecnativa**
cc @Tecnativa TT44907

@sergio-teruel please review

### CODE REVIEW

**Comment by pilarvargas-tecnativa** [comment]
I have been testing and have detected an error in the price computation, I am investigating to correct it. I am marking it as draft until it is corrected :)

**Comment by sergio-teruel** [comment]
I think that with this commit the problem is resolved
https://github.com/Tecnativa/extra-addons/commit/b9aef30516b4949c5142030c193ff31112def7b3

**Comment by pilarvargas-tecnativa** [comment]
> I think that with this commit the problem is resolved [b9aef30](https://github.com/Tecnativa/extra-addons/commit/b9aef30516b4949c5142030c193ff31112def7b3)

It was for a method to which I had not updated the arguments. Thanks :)

**Comment by pilarvargas-tecnativa** [comment]
I have done a local test by creating a product with a bill of materials and adding an extra cost, plus I have added extra cost to other products that already had a previous cost. I made a purchase and a sale (to test the price). The tests pass correctly in the local test. I don't know if I have covered all the flow of the module. Please, can you test it? @sergio-teruel @carlosdauden

**Comment by pilarvargas-tecnativa** [comment]
Removed functionality to define in a template an extra cost escalation

ping @CarlosRoca13  if you want to check

**Pull request merged**
